[package]
name = "ez"
version = "0.1.0"
edition = "2021"


[dependencies]
colored = "2"
home = "0.5.4"
inquire = "0.5.2"
indicatif = "0.17.2"
serde_json = "1.0.89"
serde = { version = "1.0.150", features = ["derive"] }
clap = { version = "4.0.27", features = ["derive"] }
reqwest = { version = "0.11.12", features = ["blocking", "json", "multipart", "stream"] } 
